	<link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700,800" rel="stylesheet"> 
	<link rel="stylesheet" href="<?=$site?>css/bootstrap.min.css">
	<link rel="stylesheet" href="<?=$site?>css/magnific-popup.css">
	<link rel="stylesheet" href="<?=$site?>css/owl.carousel.min.css">
	<link rel="stylesheet" href="<?=$site?>css/animate.css">
	<link rel="stylesheet" href="<?=$site?>css/main.css">
	<link rel="stylesheet" href="<?=$site?>css/meanmenu.min.css">
	<link rel="stylesheet" href="<?=$site?>css/icofont.min.css">
	<link rel="stylesheet" href="<?=$site?>css/responsive.css">